### ISSUE TITLE
Runtime specific replacement values for tenant configuration

### ISSUE THREAD

**Issue by NotMyself** [auth0-training/labs-vscode-extension#45]
### Description

Given the following tenant.yml configuration:

```yml
clients:
  - name: ExampleWebApp
    app_type: regular_web
    allowed_logout_urls:
      - http://localhost:3000
      - https://##CODESPACE_NAME##-37500.preview.app.github.dev
    callbacks:
      - http://localhost:3000/callback
      - https://##CODESPACE_NAME##-37500.preview.app.github.dev/callback
clientGrants:
  - client_id: ExampleWebApp
    audience: https://##AUTH0_DOMAIN##/api/v2/
    scope:
      - read:users
```

When a user attempts to configure a lab, the deployment will fail for these reasons:

1. `CODESPACE_NAME` is not available as a keyword replacement and will cause an invalid entry to be written to the tenant application registration
2. `AUTH0_DOMAIN` is not available as a keyword replacement and will cause an error to be generated attempting to write the client grants to the management api registration for the tenant.

These values are available at runtime to the extension and can be passed as default values so these substitutions work correctly.

### Describe the ideal solution

These values should be provided as default replacement values during tenant configuration deployment.
