### ISSUE TITLE
Make Codespaces Port Fowarding Domain accessible for keyword replacement

### ISSUE THREAD

**Issue by kazemicode** [auth0-training/labs-vscode-extension#51]
### Description

Github recently changed the [Codespaces port forwarding domain](https://github.blog/changelog/2023-07-14-codespaces-port-forwarding-domain-name-updates/), which broke configs of the Allowed login and Callback URLs. To avoid this in the future, we should get the value from the [Github Codespaces env variable](https://docs.github.com/en/codespaces/developing-in-codespaces/default-environment-variables-for-your-codespace) `GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN` instead of hardcoding the value. This env variable needs to be made available for [keyword replacement](https://auth0.com/docs/deploy-monitor/deploy-cli-tool/keyword-replacement).

Given the following resources.yml configuration:

```yml
clients:
  - name: ExampleWebApp
    app_type: regular_web
    allowed_logout_urls:
      - http://localhost:3000
      - https://##CODESPACE_NAME##-37500.##GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN##
    callbacks:
      - http://localhost:3000/callback
      - https://##CODESPACE_NAME##-37500.##GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN##/callback
clientGrants:
  - client_id: ExampleWebApp
    audience: https://##AUTH0_DOMAIN##/api/v2/
    scope:
      - read:users
```

When a user attempts to configure a lab, the deployment will fail because:

- `GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN` is not available as a keyword replacement and will cause an invalid entry to be written to the tenant application registration

This value are available at runtime to the extension and can be passed as default values so these substitutions work correctly.

### Describe the ideal solution

These values should be provided as default replacement values during tenant configuration deployment.

Issue is similar to previously solved issue #42
